dlang-community/dsymbol

- src/dsymbol/builtin/symbols.d
The symbol classinfo was misspelled as classInfo.
See: http://dlang.org/property.html#classinfo
I noticed the DCD 0.7.0 branch was using dsymbol instead of declaring the symbols itself, so I just changed it in both places.
> Fix spelling of classinfo.

- src/dsymbol/modulecache.d
Linux configuration directories often end with the ".d" extension, so if
you have some in your project tree and it doesn't have a dedicated
"source" directory that acts as root, addImportPaths will think that
directory is a D source file, try to read it - and crash.
> Avoid loading directories in the import paths

- src/dsymbol/modulecache.d
Use case : I create module cache when conversion tool starts
and want to cast it to immutable so that it can be reused
between parallel worker threads (without ever modifying cache again).
I have considered marking some other ModuleCache methods as const/inout
too but that quickly has become a potentially intrusive API change so
sticking only to trivial ones I actually need for now.
> Make some of ModuleCache methods const-friendly

- dub.json
dscanner requires libdparse 0.7.0-beta.6 and dsymbol requires a different version causing the build to fail. Any dscanner version that doesn't also require verison 0.7.0-beta.1 doesn't build with dub, making them useless. Not sure if you want to just change the tag to a different commit rather than bumping up the version (the last 5 versions of dscanner will then remain broken).
> Fix building dscanner with dub.

- src/dsymbol/modulecache.d
The problem is that inaccessible folders lead to a FileException when scanning directories recursively.
The fix consists into a manual recursive scanner + pokemon exception handling (for FileException only).
> make module cache scanner nothrow (DCD/319)

- src/dsymbol/conversion/first.d
My previous PR applied the fix in the wrong overload of visit.
> fix auto slices type deduction

- src/dsymbol/builtin/names.d
- src/dsymbol/conversion/second.d
Builtin constants are marked as immutable but initialized as thread locals.
This causes problems when there are several threads in application.
See #32 for details.
> fix for issue #32 - builtin constants in multithreaded app problem

- src/dsymbol/modulecache.d
Needed for https://github.com/dlang-community/DCD/issues/340.
> dsymbol.modulecache: Skip directories containing .no-dcd files

- appveyor.yml
Appveyor downloads 2.075 which is too old for the most recent EMSI containers because they use `do` for contracts.
> Disable appveyor with nightly, since it uses a too old DMD (2075)

- src/dsymbol/modulecache.d
Looks like a regression in 2.080 or to the opposite a bug revealed. Whatever it is, DCD needs this for now.
> scanner, fix possible null string after consumed by range (with 2.080)

- src/dsymbol/conversion/first.d
dparse can return incomplete `IfStatement`s to make DCD better.
> fix #77 - Crash due to #74

- dub.json
- src/dsymbol/conversion/first.d
good thing that max() was already used :sweat_smile:
> fix #85 - Add support for expression-based contracts

- src/dsymbol/conversion/second.d
While looking around because of #81, I found that some `DSymbol`'s don't seem to be ever freed: the `lastSuffix`'s created during the loop (apart from the last one) are types that are not owned by any other `DSymbol` instance, and will probably never get freed.
Maybe I'm wrong on this, I've never touched this code before; but it looks quite fishy to me.
> Fix potential memory leak

- src/dsymbol/modulecache.d
This PR would introduce two changes (and a small typo fix):
**The first:**
Implementing `ModuleCache.clear()`: from what I see, it looks like `~this()` already had almost all it needed. I simply moved the code over, added a proper `.clear()` call for `cache`, `deferredSymbols` and `importPaths`, and called `clear()` from `~this()`.
**The second:**
Adding `ModuleCache.removeImportPaths(string[] paths)`: this can be useful in several cases. For example, in Atom and VSCode, a user can have multiple folders open at the same time; and when they close one of them, clearing symbols from that folder would make sense.
Right now, listing all symbols from all folders will still show symbols from the folder that has just been removed, imports from removed dependencies will still be shown, etc. This …
> Implement cache clearing facilities

- src/dsymbol/conversion/package.d
Problem has started when support was added for the `do` keyword. Then it has continued when support for expressions - contracts was added.
> mess in simple parser, will fix, dcd #489 and dcd #523

- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
Previously a lowered NewExpression was set as the target .assignExpression member while the target had to be **directly** patched
> fixup new anonymous class lowering

- src/dsymbol/string_interning.d
The error appeared when addapting DCD to dparse 0.10.4. older compilers fail to compile because hashOf in this case is only safe from DMDFE 2.083.
See [(previous) GH release building log](https://travis-ci.org/dlang-community/DCD/jobs/451289735#L529).
> do not use `hashOf` for now because it's not `@safe` and breaks DCD

- .travis.yml
[Travis machines only have 2 cores anyway](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system), so allowing ninja to start up to 8 processes at the same time doesn't increases the compilation speed, and leads to atrocious memory usage that has made builds fail recently.
Ninja auto-detects the number of processors a machine has, so by not telling it how many processes to launch it will uses the 2 cores automatically.
> Reduce the number of parallel compilations in CI

- src/dsymbol/conversion/package.d
From [what is said in libdparse](https://github.com/dlang-community/libdparse/blob/b3a6f843457bedebc929a7fcb85529f397c73ad3/src/dparse/parser.d#L3093), `SimpleParser` needs to be updated whenever `parseFunctionBody()` is changed in libdparse.
With the changes of DIP1009, I think it needs to override `parseSpecifiedFunctionBody()` instead, as function literals and delegates now have a `SpecifiedFunctionBody` instead of a `FunctionBody`.
> Skip over specified function bodies

- src/dsymbol/conversion/package.d
which would appear in parseBlockStatement.
required to fix DCD regression.
> fix skipping contract not correct with bodyless func and possible segfault

- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
Template value parameters didn't work because the acSymbol was not put in the scope. Easy fix (#108).
Otherwise add the code so that a TemplateTypeParameter that must implicitly convert to a type get at least the base type completions. (#106)
> solve template type parameters that implicitly converts to something

- src/dsymbol/conversion/first.d
- src/dsymbol/symbol.d
Stores ditto documentation using their actual documentation and has a special ditto flag on the documentation strings.
This is not backwards compatible with any code relying on documentation being "ditto" instead of the actual documentation, otherwise it's backwards compatible.
> Implement special ditto documentation handling

- src/dsymbol/symbol.d
This fixes handling of getting completions from empty modules.
> dsymbol.symbol: Fix segmentation fault when querying empty symbol list

- src/dsymbol/builtin/names.d
- src/dsymbol/conversion/first.d
- src/dsymbol/conversion/second.d
- src/dsymbol/tests.d
Note array literal construction a postfix operation in the breadcrumb chain, greatly simplifying its handling.
> Improve handling of array literals

- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
This will fix https://github.com/dlang-community/D-Scanner/issues/749 and possible DCD crash when compiled with assertions on.
> fix insertion of bad lookups due to new anon class expr

- dub.json
- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
This will fix, (but not yet please dear GH) https://github.com/dlang-community/D-Scanner/issues/738
> fix wrong aliasName breadcrumb inserted when bad code causes messed scopes

- src/dsymbol/builtin/names.d
- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
not a critical feature, rather just to make the things correctly
```d
auto v = [];    // initializer
v ~= [];        // literal
static assert (is(typeof(v) == void[]));
static assert (is(typeof([]) == void[]));  
```
> fix #130 - empty array literals are not solved as `void[]`

- src/dsymbol/modulecache.d
- src/dsymbol/tests.d
Since strings representing the module name are actually `istring` we can store the first character of the module being cached.
> Make `ModuleCache` recursion guard using `char` ptr instead of `string`

- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
This will fix this DCD issue : https://github.com/dlang-community/DCD/issues/593
> fix anonymous struct members not located in the parent symbol

- src/dsymbol/conversion/first.d
- src/dsymbol/scope_.d
- src/dsymbol/semantic.d
- src/dsymbol/symbol.d
Moves protection into DSymbol
Needed for dlang-community/DCD#598
> Symbol protection

- .editorconfig
- .gitignore
- dub.json
- src/dsymbol/builtin/names.d
- src/dsymbol/builtin/symbols.d
- src/dsymbol/cache_entry.d
- src/dsymbol/conversion/first.d
- src/dsymbol/deferred.d
- src/dsymbol/modulecache.d
- src/dsymbol/scope_.d
- src/dsymbol/semantic.d
- src/dsymbol/string_interning.d
- src/dsymbol/symbol.d
- src/dsymbol/tests.d
When a thread terminates, global malloc-allocated things remain. Furthermore, destructors of thread-local objects aren't invoked either!
Tested on `serve-d` using Valgrind Massif.
I hope you won't mind that I've done some refactoring and other stuff in the meantime.
> Fixes for memory leaks on thread termination + refactoring

- src/dsymbol/builtin/names.d
- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
It doesn't work for lambdas.
Argument list visitor handles cases like `auto a = g({...});` and `auto a = g(new class {...});` - symbols inside such blocks were invisible to dcd before this patch.
> Implement completion for function literal parameters

- src/dsymbol/conversion/first.d
- src/dsymbol/conversion/second.d
- src/dsymbol/scope_.d
- src/dsymbol/symbol.d
- src/dsymbol/tests.d
I guess it also fixes a weird bug when loads of unrelated symbols appeared in autocomplete lists. For example, I do `import std.stdio : File` in module A, then use A in module B, and suddenly `File` methods appear everywhere in B.
> Fix public selective imports

- src/dsymbol/modulecache.d
* adds windows & posix specific file/dir checks with existence, drops previous try-catch based code which improves performance in debug mode like x50 for the `resolveImportLocation` function
* exact `.d` matches inside import paths now immediately return on the first import path instead of returning at the end of the function being equal to the path inside the last matching import path
* file import paths no longer perform any IO if the path wouldn't match anyway
* remove array allocations for alternatives, now uses simpler code which can also return early
This gives a big speed up improvement in DCD on Windows:
|   | Old (Debug) | New (Debug) | Old (Release) | New (Release) |
|---:|------------:|------------:|--------------:|--------------:|
|   | 457792      | 5600        | 98314 …
> 83x speed up `resolveImportLocation`

- src/dsymbol/conversion/first.d
Print the string directly instead of the `istring`.
Old: `Could not resolve location of module 'immutable(istring)("gcc/builtins")'`
New: `Could not resolve location of module 'gcc/builtins'`
> Fix the error message printed when a module cannot be found

- src/dsymbol/conversion/package.d
This fixes a few bugs in the specialized parser that is run on code that is imported (i.e. the function bodies and unit test bodies are skipped). Returning `null` from these functions caused the parser to go into error recovery mode and skip ahead to the nearest semicolon or closing brace. This causes dsymbol to actually fail to correctly parse well-formed code, leading to problems like https://github.com/dlang-community/DCD/issues/620.
In addition to not returning `null` from the `unittest` parser, this change also fixes a problem where some forms of functions with contracts were skipped incorrectly, which also caused them to be missing in autocomplete lists in DCD. There are test cases in the linked DCD draft pull request. dsymbol's unit test coverage is pretty bad and I don't intend to …
> Fix parsing bugs that caused symbol visibility to be incorrect.

- .travis.yml
broken dependencies causes builds to fail
> disable meson tests for now

- src/dsymbol/conversion/first.d
- src/dsymbol/tests.d
variable was never inserted, so test didn't fail because there was no check that all variables have been covered.
> Fix void[] initializer and test for it

- src/dsymbol/modulecache.d
This reverts accidental rename of this public symbol at https://github.com/dlang-community/dsymbol/commit/b090b70c4775cd5ba8865d8a450b1fbef84376b4#diff-65f2448b99faadbee0fa35083cd6ed8308a763082ca322f3ce2d6fb8908041cdR51.
Ready for merging and tagging, @WebFreak001.
> Rename SemanticAllocator to ASTAllocator

- dub.json
this should hopefully no longer be needed if we integrate dsymbol into DCD
the update in libdparse removed the stdx-allocators dependency, which we removed in dsymbol with the latest tag as well.
> update libdparse to fix issue in DCD

- src/dsymbol/conversion/first.d
- src/dsymbol/conversion/package.d
- src/dsymbol/modulecache.d
- src/dsymbol/symbol.d
- src/dsymbol/tests.d
To not rely on callTips and properly support UFCS, we need functions to store their applicable argument symbols, this PR adds does this.
> make function symbols store function parameters, needed for UFCS.
