dlang-community/dsymbol

src/dsymbol/modulecache.d

Allows passing file names as import paths instead of only directories in ModuleCache. They will directly be added using cacheModule and have a special check in resolveImportLocation.
There might be rare cases where multiple alternatives could result from `resolveImportLocation` because it only checks if the filename of the import path ends with the required module.
One example would be this: We have file `foo/bar.d` and `foo/abc/foo/bar.d`. Then `import foo.bar;` will think both of those are meant with that import.
I don't think there is a fix to this other than also adding the cwd of the file separately because the user could always mean something different. So this would be the only disadvantage of adding files.

Allowing adding files as import paths

---

src/dsymbol/conversion/first.d

Fix protection stack calls.

---

src/dsymbol/conversion/first.d
src/dsymbol/conversion/second.d

Only works for a single dimension for now (tested in DCD)

fix #14 - resolve auto arrays

---

src/dsymbol/builtin/symbols.d

`float.min` is a not a valid property.

remove the min property for floats

---

.travis.yml

Apparently we forgot to put a `travis.yml` for this repo...

Add a .travis.yml file to enable testing on Travis

---

src/dsymbol/conversion/first.d

This required ASAP to fix https://github.com/dlang-community/DCD/issues/389

fix auto slices type deduction

---

src/dsymbol/conversion/first.d

required for a DCD fix, that's https://github.com/dlang-community/DCD/issues/323

always make a symbol for last item in ForeachTypeList

---

src/dsymbol/builtin/names.d
src/dsymbol/conversion/first.d

Needed for https://github.com/dlang-community/DCD/issues/400. Already tested locally in DCD.

add support for auto bools

---

dub.json
src/dsymbol/conversion/package.d

libdparse prefers a delegate since 3 days.

fix deprecations messages related to the message function

---

.travis.yml
src/dsymbol/tests.d

This is based on the runnable module i've started to use to help with the auto array bug. The goal of this first test kind is to help enhancing auto deduction from initializers.

[WIP] starts a testing system, name + types for now

---

src/dsymbol/builtin/symbols.d

Remove deprecated reverse and sort array properties

---

dub.json

Propagates the fixes from the lower level...

update dparse version

---

src/dsymbol/tests.d

Use `generateAutocompleteTrees` with source directly instead of making a temp file.

test utils

---

src/dsymbol/conversion/second.d
src/dsymbol/tests.d

Alias resolve patch issue #51

---

src/dsymbol/conversion/first.d
src/dsymbol/tests.d

Union generated constructor patch issue #49

---

src/dsymbol/conversion/first.d
src/dsymbol/tests.d

Struct generated ctor patch issue #47

---

dub.json

I would tag this as v0.3.1 then?

Upgrade DSymbol to use containers 0.7

---

src/dsymbol/modulecache.d

known to freeze the DCD server, see https://github.com/dlang-community/DCD/issues/419

fix random stack issues due to usage of scoped

---

src/dsymbol/modulecache.d

This reverts commit eca935ddec42d1ca19bb89670375dce4434058e0.

Revert "fix random stack issues due to usage of scoped"

---

dub.json
src/dsymbol/conversion/first.d

will fix, once pulled, https://github.com/dlang-community/DCD/issues/484

add a symbol for the variables declared in a IfStatement

---

src/dsymbol/conversion/first.d

I've verified locally that this works for the case presented in https://github.com/dlang-community/DCD/issues/510.
The code added is adapted from visit of an `AliasDeclaration`, after verifying that using an `alias` instead of of a named `mixin` produces the expected results.

add support for named mixin, needed for DCD #510

---

.travis.yml
meson.build
subprojects/dcontainers.wrap
subprojects/dparse.wrap
subprojects/stdx-allocator.wrap

Based on @ximion work on https://github.com/dlang-community/containers/commit/fc97b589e485d6e80e6f17c828abaa6c9fb27f35

Add Meson build definition

---

meson.build

Fix dsymbol version from meson.build file

---

subprojects/stdx-allocator.wrap

head revision requires to add mir-core as a submodule

update stdx alloc wrap file

---

src/dsymbol/conversion/first.d

This has been bothering me on serve-d for months

Fix empty ModuleDeclaration visit crashing

---

src/dsymbol/modulecache.d

Avoid the up-front cost of scanning potentially arbitrarily large directory trees (which may include network filesystems and other things best not touched).
Probably fixes https://github.com/dlang-community/DCD/issues/316.

dsymbol.modulecache: Scan added imports on-demand

---

src/dsymbol/builtin/symbols.d
src/dsymbol/conversion/first.d
src/dsymbol/conversion/second.d
src/dsymbol/symbol.d
src/dsymbol/tests.d

I dont see how to test properly here so a good test will be added in DCD.

fix #115 - Add completion to variadic template parameters

---

src/dsymbol/conversion/first.d
src/dsymbol/tests.d

Fix getting type of array index from initializer

---

.travis.yml

This was added to other repos too, this one was forgotten apparently

Also make travis CI test when there's a tag

---

dub.json
meson.build
subprojects/dcontainers.wrap
subprojects/stdx-allocator.wrap

The process of removing the fixed version of the containers package must start here.

upgrade dependencies

---

src/dsymbol/conversion/first.d
src/dsymbol/tests.d

This will fix this DCD issue : https://github.com/dlang-community/DCD/issues/592

also resolve inherited types when used in access chains

---

src/dsymbol/modulecache.d

```
std.file.exists is insufficient to ensure that querying the attributes
at that path will succeed.  Not only is doing so a TOCTOU bug, but,
std.file.exists performs an lstat call, whereas isFile/isDir performs
a stat call (which we do need to do to support symlinks); this will
result in an exception when the path is a broken symlink, as the
former will succeed while the latter will fail.
Fix this by removing explicit std.file.exists checks, and replacing
them with a wrapper which catches and handles error conditions,
treating them as the path not satisfying the desired property.
```

dsymbol.modulecache: Ignore errors when querying file attributes

---

src/dsymbol/conversion/first.d
src/dsymbol/tests.d

Fix conditional decl protections tainting scope

---

.gitmodules
.travis.yml
dub.json

tests both minimum and maximum allowed libdparse versions with dub

use test_with_package & bump libdparse to <0.16.0

---

src/dsymbol/conversion/package.d

Fixes DCD tests and autocompletion with functions with contracts.

fix conversion/package.d function bodys
